import React, { useContext } from "react";
import type { NextPage } from 'next'
import Head from 'next/head'

import { NavigationContext } from "@components/context/NavigationProvider";

const Home: NextPage = () => {
  const { step, onChangeStep } = useContext(NavigationContext);

  console.log("------ step ------", step)

  return (
    <>
      <Head>
        <title>LaBotanik</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <h1>Hello world</h1>
    </>
  )
}

export default Home
